// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello2.proto

package userInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import "net/rpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38d7a436d63edd8, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Input) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Output struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38d7a436d63edd8, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Output) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Output) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Output) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*Input)(nil), "myUserInfo.Input")
	proto.RegisterType((*Output)(nil), "myUserInfo.Output")
}

func init() { proto.RegisterFile("hello2.proto", fileDescriptor_d38d7a436d63edd8) }

var fileDescriptor_d38d7a436d63edd8 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0xcd, 0xc9,
	0xc9, 0x37, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0xad, 0x0c, 0x2d, 0x4e, 0x2d,
	0xf2, 0xcc, 0x4b, 0xcb, 0x57, 0xd2, 0xe6, 0x62, 0xf5, 0xcc, 0x2b, 0x28, 0x2d, 0x11, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xf8,
	0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x94, 0x62,
	0xb8, 0xd8, 0xfc, 0x4b, 0x4b, 0x40, 0xaa, 0x21, 0x32, 0x8c, 0x30, 0x19, 0xb8, 0x6e, 0x26, 0x24,
	0xdd, 0x12, 0x5c, 0xec, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0xcc, 0x60, 0x61, 0x18,
	0x57, 0x48, 0x84, 0x8b, 0xb5, 0x20, 0x23, 0x3f, 0x2f, 0x55, 0x82, 0x05, 0x2c, 0x0e, 0xe1, 0x18,
	0x39, 0x73, 0x71, 0x83, 0x9c, 0x15, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc2, 0xc5,
	0x9d, 0x9e, 0x5a, 0x02, 0x73, 0xa8, 0x90, 0xa0, 0x1e, 0xc2, 0xd5, 0x7a, 0x60, 0x27, 0x4b, 0x09,
	0x21, 0x0b, 0x41, 0x1c, 0xe6, 0x24, 0x12, 0x25, 0x94, 0x5b, 0x19, 0x90, 0x98, 0x9c, 0x9d, 0x98,
	0x9e, 0xaa, 0x5f, 0x0a, 0x95, 0x4c, 0x62, 0x03, 0x7b, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x9c, 0x63, 0x99, 0xca, 0x08, 0x01, 0x00, 0x00,
}

type UserServiceInterface interface {
	GetUserInfo(in *Input, out *Output) error
}

func RegisterUserService(srv *rpc.Server, x UserServiceInterface) error {
	if err := srv.RegisterName("UserService", x); err != nil {
		return err
	}
	return nil
}

type UserServiceClient struct {
	*rpc.Client
}

var _ UserServiceInterface = (*UserServiceClient)(nil)

func DialUserService(network, address string) (*UserServiceClient, error) {
	c, err := rpc.Dial(network, address)
	if err != nil {
		return nil, err
	}
	return &UserServiceClient{Client: c}, nil
}

func (p *UserServiceClient) GetUserInfo(in *Input, out *Output) error {
	return p.Client.Call("UserService.GetUserInfo", in, out)
}
